default:
  batchmode: false
  cachedb: "sqlite"
  cloud:
    cachedir: "/folders/1b2h5hJlarNMkxdUyJLO5pPUwrQV8m626"
    googleuser: ""
    usecloud: false
  gitpkgpath: "~/GitHub"
  mapresfact: 1
  paths:
    activedir: "~/GitHub/LandWeb"
    scratchdir: "/tmp/scratch/LandWeb"
  plot: true
  postprocess: false
  rep: 1
  studyarea: "random"
  scenariodisp: "" # "aspenDispersal", "highDispersal", "noDispersal", or "" for default
  scenariofire: "" # "equalROS", "logROS", or "" for default
  restartr: false

profile:
  params:
    endtime: !expr 20
    successiontimestep: !expr 10
    summaryperiod: !expr c(10, 20)
    summaryinterval: !expr 10
    timeseriestimes: !expr 10
  plot: false
  rep: 1
  studyarea: "Tolko_SK"
  scenariodisp: ""
  scenariofire: ""

test:
  params:
    endtime: !expr 300
    successiontimestep: !expr 10
    summaryperiod: !expr c(250, 300)
    summaryinterval: !expr 10
    timeseriestimes: !expr 201:210
  plot: true

production:
  batchmode: true ## if true, don't specify rep, studyarea, scenario*
  cloud:
    usecloud: false
  params:
    endtime: !expr 1000
    successiontimestep: !expr 10
    summaryperiod: !expr c(700, 1000)
    summaryinterval: !expr 100
    timeseriestimes: !expr 601:650
  plot: false
  #rep: 1
  #studyarea: "LandWeb"
  #scenariodisp: "highDispersal"
  #scenariofire: "logROS"

alex:
  inherits: production
  cachedb: "postgresql"
  cloud:
    googleuser: "alex.chubaty@gmail.com"
    #googleuser: "achubaty@for-cast.ca"
    usecloud: false
  gitpkgpath: "~/GitHub/PredictiveEcology"
  paths:
    scratchdir: "/mnt/scratch/LandWeb"
  slackchannel: "@alex.chubaty"

eliot:
  inherits: production
  cachedb: "sqlite"
  cloud:
    googleuser: "eliotmcintire@gmail.com"
    usecloud: true
  gitpkgpath: "~/GitHub"
  slackchannel: "@eliotmcintire"
